name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: rafael877
          outputs: |
            dist/snake-neon.svg?color_snake=#00F7FF&color_dots=#0d1117,#003f5c,#00F7FF,#00cfff,#66ffff

      - name: Push Snake
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
